CREATE DATABASE C1_BLOG;

USE C1_BLOG;

GRANT ALL PRIVILEGES ON C1_BLOG TO C1@localhost IDENTIFIED BY 'Amina';

CREATE TABLE user(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50),
	password VARCHAR(50)
);

CREATE TABLE blog(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	blog_name VARCHAR(50),
	user_id INT
);

CREATE TABLE post(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50),
	body TEXT,
	date_created DATETIME DEFAULT NULL,
	date_modified DATETIME DEFAULT NULL,
	blog_id INT
);

CREATE TABLE comment(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	content TEXT,
	date_created DATETIME DEFAULT NULL,
	date_modified DATETIME DEFAULT NULL,
	post_id INT,
	user_id INT
);

