CREATE DATABASE C1_BLOG;

USE C1_BLOG;

GRANT ALL PRIVILEGES ON C1_BLOG.* TO C1@localhost IDENTIFIED BY 'Amina';

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50),
	password VARCHAR(50),
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL
);

CREATE TABLE blogs (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	blog_name VARCHAR(50),
	user_id INT
);

CREATE TABLE posts (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50),
	body TEXT,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL,
	blog_id INT
);

CREATE TABLE comments (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	content TEXT,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL,
	post_id INT,
	user_id INT
);

